command: ["python", "app.py"]

env:
  # PostgreSQL Database (from DatabaseCatalog)
  - name: PGDATABASE
    value: "pg_lakebase_kunal-gaurav"  # ✅ Fixed
  
  # Database User
  - name: PGUSER
    value: "ca1b03c4-8920-4569-8b7b-b5b0825ee3af"
  
  # PostgreSQL Host (from Lakebase instance)
  - name: PGHOST
    value: "instance-f60d62f1-e44a-43c7-813f-58138e0552fd.database.cloud.databricks.com"
  
  # PostgreSQL Port
  - name: PGPORT
    value: "5432"
  
  # SSL Mode (required for Databricks)
  - name: PGSSLMODE
    value: "require"
  
  # Application Name
  - name: PGAPPNAME
    value: "iot_dashboard"
  
  # Table Configuration
  - name: SCHEMA_NAME
    value: "telcom"
  
  - name: TABLE_NAME
    value: "iot_data_synced"
  
  # Lakebase Instance Name (for OAuth token generation)
  - name: INSTANCE_NAME
    value: "kunal-gaurav-lakebase-instance"